# 10 Minutes Pandas [link](https://pandas.pydata.org/docs/user_guide/10min.html#min)

In [1]:
import pandas as pd
import numpy as np

In [2]:
# series
s = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [3]:
# dataframs (index are the keyes)  (columns are the titles)
dates = pd.date_range('20130101', periods=6) #year-month-day
print(dates)

print()
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=['A', 'B', 'C', 'D'])
df

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')



A         B         C         D
2013-01-01 -0.107059  0.123826  1.494973  0.694259
2013-01-02  0.489124 -1.584452  0.740508 -1.307688
2013-01-03 -0.917904  0.333546  0.345352  0.122169
2013-01-04  0.028661  1.251974 -0.201867 -0.767895
2013-01-05  0.866957  1.534359  0.834069  1.244963
2013-01-06  0.907876  1.136002 -1.794488  1.000856

In [4]:
# creating data frame form dictionary
df2 = pd.DataFrame(
    {
        'A': 1.0,
        'B': pd.Timestamp('20130102'),
        'C': pd.Series(1, index=list(range(4)), dtype='float32'),
        'D': np.array([3]*4, dtype=np.int32),
        'E': pd.Categorical(['test', 'train', 'test', 'train']),
        'F': 'foo'
    }
)
#datafram columns type
print(df2.dtypes)
df2

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object


A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [5]:
# accessing a column returning a series
print(df2.C)
print(df2['C'])

#displaying index (keys)
print('\n', df2.index)
print(list(df2.index))

#displaying columns
print('\n', df2.columns)
print(list(df2.columns))

0    1.0
1    1.0
2    1.0
3    1.0
Name: C, dtype: float32
0    1.0
1    1.0
2    1.0
3    1.0
Name: C, dtype: float32

 Int64Index([0, 1, 2, 3], dtype='int64')
[0, 1, 2, 3]

 Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')
['A', 'B', 'C', 'D', 'E', 'F']


In [151]:
# accessing raws
df[:3]

A          B         C  D    F
2013-01-01 -0.107059   0.123826  1.494973  0  NaN
2013-01-02  0.000000  11.000000  0.740508  1  1.0
2013-01-03 -0.917904   0.333546  0.345352  2  2.0

In [6]:
# converting data frame to numpy
'''
    if all data types are the same pandas will return a numpy array with the save datatype
    if columns are not the same datatype will return them as object and we nedd to cast every column in order to use it
        in addition it is heavy operatoin
'''
print(df.to_numpy())
np_object = df2.to_numpy() # array of objects
type(np_object[0][1])

[[-0.10705883  0.12382557  1.49497289  0.69425869]
 [ 0.48912352 -1.58445247  0.74050835 -1.30768761]
 [-0.91790385  0.33354598  0.34535176  0.12216904]
 [ 0.02866114  1.25197446 -0.20186709 -0.76789501]
 [ 0.86695746  1.53435857  0.83406895  1.24496265]
 [ 0.90787623  1.13600231 -1.79448845  1.00085557]]


pandas._libs.tslibs.timestamps.Timestamp

In [7]:
# describing the data
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.211276  0.465876  0.236424  0.164444
std    0.693124  1.144293  1.142261  1.018432
min   -0.917904 -1.584452 -1.794488 -1.307688
25%   -0.073129  0.176256 -0.065062 -0.545379
50%    0.258892  0.734774  0.542930  0.408214
75%    0.772499  1.222981  0.810679  0.924206
max    0.907876  1.534359  1.494973  1.244963

In [8]:
# transposing
df.T

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -0.107059    0.489124   -0.917904    0.028661    0.866957    0.907876
B    0.123826   -1.584452    0.333546    1.251974    1.534359    1.136002
C    1.494973    0.740508    0.345352   -0.201867    0.834069   -1.794488
D    0.694259   -1.307688    0.122169   -0.767895    1.244963    1.000856

In [9]:
# sort by index of column
'''
axis=0 sort raws by index(keys)
axis=1 sort columns by column's mean value
'''
df.sort_index(axis=1, ascending=False)

D         C         B         A
2013-01-01  0.694259  1.494973  0.123826 -0.107059
2013-01-02 -1.307688  0.740508 -1.584452  0.489124
2013-01-03  0.122169  0.345352  0.333546 -0.917904
2013-01-04 -0.767895 -0.201867  1.251974  0.028661
2013-01-05  1.244963  0.834069  1.534359  0.866957
2013-01-06  1.000856 -1.794488  1.136002  0.907876

In [10]:
# sort by a specific columns
df.sort_values(by='B')

A         B         C         D
2013-01-02  0.489124 -1.584452  0.740508 -1.307688
2013-01-01 -0.107059  0.123826  1.494973  0.694259
2013-01-03 -0.917904  0.333546  0.345352  0.122169
2013-01-06  0.907876  1.136002 -1.794488  1.000856
2013-01-04  0.028661  1.251974 -0.201867 -0.767895
2013-01-05  0.866957  1.534359  0.834069  1.244963

# Selection

## Selection by label 
### (i.e: index_name\s, or column_name\s)  = `df.loc['20130101', 'A']`
### using: `DataFrame.loc[]` or, `DataFrame.at[]`

In [11]:
# get a column -> return a series
print(df['A'])
print(df.A)

2013-01-01   -0.107059
2013-01-02    0.489124
2013-01-03   -0.917904
2013-01-04    0.028661
2013-01-05    0.866957
2013-01-06    0.907876
Freq: D, Name: A, dtype: float64
2013-01-01   -0.107059
2013-01-02    0.489124
2013-01-03   -0.917904
2013-01-04    0.028661
2013-01-05    0.866957
2013-01-06    0.907876
Freq: D, Name: A, dtype: float64


In [12]:
# selection of raws -> return a Dataframe NOTE df[0] is not allowed use df.loc
df[0:3] #using normal python indexing (end=3 is not includes)
df['20130101':'20130103'] #from start until end (end in includes unlike python indexing)

A         B         C         D
2013-01-01 -0.107059  0.123826  1.494973  0.694259
2013-01-02  0.489124 -1.584452  0.740508 -1.307688
2013-01-03 -0.917904  0.333546  0.345352  0.122169

In [13]:
df[:1]

A         B         C         D
2013-01-01 -0.107059  0.123826  1.494973  0.694259

In [14]:
# seleting a single raw -> return:
'''
    a series: given a single index
    a DataFrame given multiple indcies
'''
indcies = df.index
print(df.loc[indcies[0]]) # a Series
df.loc[indcies[0:3]] # a DataFrame

A   -0.107059
B    0.123826
C    1.494973
D    0.694259
Name: 2013-01-01 00:00:00, dtype: float64


A         B         C         D
2013-01-01 -0.107059  0.123826  1.494973  0.694259
2013-01-02  0.489124 -1.584452  0.740508 -1.307688
2013-01-03 -0.917904  0.333546  0.345352  0.122169

In [15]:
# slecting multiple axis by label (column)
df.loc[:,['A', 'B']] # input is (index, columns list)

A         B
2013-01-01 -0.107059  0.123826
2013-01-02  0.489124 -1.584452
2013-01-03 -0.917904  0.333546
2013-01-04  0.028661  1.251974
2013-01-05  0.866957  1.534359
2013-01-06  0.907876  1.136002

In [16]:
# selecting by index and columns
df.loc['20130101': '20130104',['A', 'B']] # input is (index, columns list)

A         B
2013-01-01 -0.107059  0.123826
2013-01-02  0.489124 -1.584452
2013-01-03 -0.917904  0.333546
2013-01-04  0.028661  1.251974

In [17]:
#selecting specifc set of raws
df.loc[['20130101', '20130104'],['A', 'B']] # input is (index, columns list)

A         B
2013-01-01 -0.107059  0.123826
2013-01-04  0.028661  1.251974

In [18]:
# getting a cell 
val = df.loc['20130101', 'A']
print(type(val))
val

<class 'numpy.float64'>


-0.10705882819512673

In [19]:
# fast access similar to the above 
df.at['20130101', 'A']

-0.10705882819512673

## Selecting by position 
## (i.e: index of index(key)\s, and index of column\s) = `df.iloc[0, 0]`
### `DataFrame.iloc[]`, or `DataFrame.iat[]`

In [20]:
# selecting a row
'''
return: 
    a Series if selecting a single raw
    a DataFrame if selecting multiple raws, or columns
'''
df.iloc[3] # forth raw

A    0.028661
B    1.251974
C   -0.201867
D   -0.767895
Name: 2013-01-04 00:00:00, dtype: float64

In [21]:
#selecting multiple raws and columns using interger slicing
df.iloc[0:4, 0: 3]

A         B         C
2013-01-01 -0.107059  0.123826  1.494973
2013-01-02  0.489124 -1.584452  0.740508
2013-01-03 -0.917904  0.333546  0.345352
2013-01-04  0.028661  1.251974 -0.201867

In [22]:
# specific raws and columns
df.iloc[[0, 4], [0, 3]]

A         D
2013-01-01 -0.107059  0.694259
2013-01-05  0.866957  1.244963

In [23]:
# specifc raws and all columns
df.iloc[[0, 4], :]

A         B         C         D
2013-01-01 -0.107059  0.123826  1.494973  0.694259
2013-01-05  0.866957  1.534359  0.834069  1.244963

In [24]:
# all raws and specifc columns
df.iloc[:, [0, 3]]

A         D
2013-01-01 -0.107059  0.694259
2013-01-02  0.489124 -1.307688
2013-01-03 -0.917904  0.122169
2013-01-04  0.028661 -0.767895
2013-01-05  0.866957  1.244963
2013-01-06  0.907876  1.000856

In [25]:
# access a cell i.e: scaler
df.iloc[0, 0]

-0.10705882819512673

In [26]:
# fast access to scaler
df.iat[0, 0]

-0.10705882819512673

## Boolean Indexing (same as numpy)

In [27]:
x = np.random.rand(4, 4, 3)
print(x)
x[x>.9]

[[[0.97686495 0.01726837 0.98613432]
  [0.61375338 0.55262301 0.96807709]
  [0.29735726 0.96324898 0.17199886]
  [0.54527341 0.00666131 0.47582935]]

 [[0.82675305 0.43822629 0.95914506]
  [0.96575994 0.27588765 0.12798653]
  [0.18660753 0.27789124 0.73808686]
  [0.27956558 0.15161987 0.94077503]]

 [[0.02185915 0.76696153 0.83422711]
  [0.2355105  0.54074147 0.30212928]
  [0.80223693 0.73739798 0.86919298]
  [0.55115328 0.06449159 0.62790111]]

 [[0.48530085 0.39106073 0.57144144]
  [0.60980393 0.64172833 0.23793559]
  [0.27297171 0.44262406 0.88810444]
  [0.76789666 0.490309   0.69290301]]]


array([0.97686495, 0.98613432, 0.96807709, 0.96324898, 0.95914506,
       0.96575994, 0.94077503])

In [40]:
# boolean indexng 
print(df.loc[:,'A']>0)
print()
df[df.loc[:, 'A']>0]

2013-01-01    False
2013-01-02     True
2013-01-03    False
2013-01-04     True
2013-01-05     True
2013-01-06     True
Freq: D, Name: A, dtype: bool



A         B         C         D
2013-01-02  0.489124 -1.584452  0.740508 -1.307688
2013-01-04  0.028661  1.251974 -0.201867 -0.767895
2013-01-05  0.866957  1.534359  0.834069  1.244963
2013-01-06  0.907876  1.136002 -1.794488  1.000856

In [47]:
# boolean indexing
print(df.loc[:,'A':'C'] >0)
print(df[df.loc[:,'A':'C'] >0])

# correct way
df[df['A']>0][df['B']>0]

                A      B      C
2013-01-01  False   True   True
2013-01-02   True  False   True
2013-01-03  False   True   True
2013-01-04   True   True  False
2013-01-05   True   True   True
2013-01-06   True   True  False
                   A         B         C   D
2013-01-01       NaN  0.123826  1.494973 NaN
2013-01-02  0.489124       NaN  0.740508 NaN
2013-01-03       NaN  0.333546  0.345352 NaN
2013-01-04  0.028661  1.251974       NaN NaN
2013-01-05  0.866957  1.534359  0.834069 NaN
2013-01-06  0.907876  1.136002       NaN NaN


/tmp/ipykernel_6943/2630552352.py:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['A']>0][df['B']>0]


A         B         C         D
2013-01-04  0.028661  1.251974 -0.201867 -0.767895
2013-01-05  0.866957  1.534359  0.834069  1.244963
2013-01-06  0.907876  1.136002 -1.794488  1.000856

In [48]:
# using isin
df2 = df.copy()
df2['E'] = ["one", "one", "two", "three", "four", "three"]
df2

A         B         C         D      E
2013-01-01 -0.107059  0.123826  1.494973  0.694259    one
2013-01-02  0.489124 -1.584452  0.740508 -1.307688    one
2013-01-03 -0.917904  0.333546  0.345352  0.122169    two
2013-01-04  0.028661  1.251974 -0.201867 -0.767895  three
2013-01-05  0.866957  1.534359  0.834069  1.244963   four
2013-01-06  0.907876  1.136002 -1.794488  1.000856  three

In [51]:
print(df2['E'].isin(['one', 'four']))
df2[df2['E'].isin(['one', 'four'])]

2013-01-01     True
2013-01-02     True
2013-01-03    False
2013-01-04    False
2013-01-05     True
2013-01-06    False
Freq: D, Name: E, dtype: bool


A         B         C         D     E
2013-01-01 -0.107059  0.123826  1.494973  0.694259   one
2013-01-02  0.489124 -1.584452  0.740508 -1.307688   one
2013-01-05  0.866957  1.534359  0.834069  1.244963  four

## Setting

### by label using: `DataFrame.loc[] = new_value`, `DataFrame.at[]= new_value`
### by value  using: `DataFrame.iloc[] = new_value`, `DataFrame.iat[]= new_value`

In [60]:
# setting an elemnt in a series
s1 = pd.Series(np.arange(1, 7, dtype=np.int32), index=pd.date_range('20130102', periods=6))
print(s1)
df['F'] = s1
df

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int32


A         B         C         D    F
2013-01-01 -0.107059  0.123826  1.494973  0.694259  NaN
2013-01-02  0.489124 -1.584452  0.740508 -1.307688  1.0
2013-01-03 -0.917904  0.333546  0.345352  0.122169  2.0
2013-01-04  0.028661  1.251974 -0.201867 -0.767895  3.0
2013-01-05  0.866957  1.534359  0.834069  1.244963  4.0
2013-01-06  0.907876  1.136002 -1.794488  1.000856  5.0

In [62]:
# setting the second raw, 'A' by "label"
indcies = df.index
df.loc[indcies[1], 'A'] = 0 # same as 'at'
df

A         B         C         D    F
2013-01-01 -0.107059  0.123826  1.494973  0.694259  NaN
2013-01-02  0.000000 -1.584452  0.740508 -1.307688  1.0
2013-01-03 -0.917904  0.333546  0.345352  0.122169  2.0
2013-01-04  0.028661  1.251974 -0.201867 -0.767895  3.0
2013-01-05  0.866957  1.534359  0.834069  1.244963  4.0
2013-01-06  0.907876  1.136002 -1.794488  1.000856  5.0

In [63]:
# setting second raw and second columns by "value => index"
df.iloc[1, 1] = 11
df

A          B         C         D    F
2013-01-01 -0.107059   0.123826  1.494973  0.694259  NaN
2013-01-02  0.000000  11.000000  0.740508 -1.307688  1.0
2013-01-03 -0.917904   0.333546  0.345352  0.122169  2.0
2013-01-04  0.028661   1.251974 -0.201867 -0.767895  3.0
2013-01-05  0.866957   1.534359  0.834069  1.244963  4.0
2013-01-06  0.907876   1.136002 -1.794488  1.000856  5.0

In [64]:
# setting a whole column
df.loc[:, 'D'] = np.arange(len(df))
df

/tmp/ipykernel_6943/3768638159.py:2: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[:, 'D'] = np.arange(len(df))


A          B         C  D    F
2013-01-01 -0.107059   0.123826  1.494973  0  NaN
2013-01-02  0.000000  11.000000  0.740508  1  1.0
2013-01-03 -0.917904   0.333546  0.345352  2  2.0
2013-01-04  0.028661   1.251974 -0.201867  3  3.0
2013-01-05  0.866957   1.534359  0.834069  4  4.0
2013-01-06  0.907876   1.136002 -1.794488  5  5.0

In [66]:
# usig 'where' operation
df2 = df.copy()
df2[df2 >0 ] = df2 + 999
df2

A            B            C     D       F
2013-01-01   -0.107059   999.123826  1000.494973     0     NaN
2013-01-02    0.000000  1010.000000   999.740508  1000  1000.0
2013-01-03   -0.917904   999.333546   999.345352  1001  1001.0
2013-01-04  999.028661  1000.251974    -0.201867  1002  1002.0
2013-01-05  999.866957  1000.534359   999.834069  1003  1003.0
2013-01-06  999.907876  1000.136002    -1.794488  1004  1004.0

## missing data

In [76]:
## reindex (i.e taking parts of the dataframe, or adding columns , or raws)
df1 = df.reindex(index=df.index, columns=list(df.columns) + ['E'])
df1.iloc[0, [-2, -1]] = [-1, 1]
df1

A          B         C  D    F    E
2013-01-01 -0.107059   0.123826  1.494973  0 -1.0  1.0
2013-01-02  0.000000  11.000000  0.740508  1  1.0  NaN
2013-01-03 -0.917904   0.333546  0.345352  2  2.0  NaN
2013-01-04  0.028661   1.251974 -0.201867  3  3.0  NaN
2013-01-05  0.866957   1.534359  0.834069  4  4.0  NaN
2013-01-06  0.907876   1.136002 -1.794488  5  5.0  NaN

In [77]:
# dropiing np.nan values
df1.dropna(how='any') # droping any raw that have no data

A         B         C  D    F    E
2013-01-01 -0.107059  0.123826  1.494973  0 -1.0  1.0

In [78]:
# drping a whole raw that have all columns have nan value
df1.iloc[-1, :] = np.nan
print(df1)
df1.dropna(how='all')

                   A          B         C    D    F    E
2013-01-01 -0.107059   0.123826  1.494973  0.0 -1.0  1.0
2013-01-02  0.000000  11.000000  0.740508  1.0  1.0  NaN
2013-01-03 -0.917904   0.333546  0.345352  2.0  2.0  NaN
2013-01-04  0.028661   1.251974 -0.201867  3.0  3.0  NaN
2013-01-05  0.866957   1.534359  0.834069  4.0  4.0  NaN
2013-01-06       NaN        NaN       NaN  NaN  NaN  NaN


A          B         C    D    F    E
2013-01-01 -0.107059   0.123826  1.494973  0.0 -1.0  1.0
2013-01-02  0.000000  11.000000  0.740508  1.0  1.0  NaN
2013-01-03 -0.917904   0.333546  0.345352  2.0  2.0  NaN
2013-01-04  0.028661   1.251974 -0.201867  3.0  3.0  NaN
2013-01-05  0.866957   1.534359  0.834069  4.0  4.0  NaN

In [79]:
# filling NaN
df1.fillna(value=99)

A          B          C     D     F     E
2013-01-01  -0.107059   0.123826   1.494973   0.0  -1.0   1.0
2013-01-02   0.000000  11.000000   0.740508   1.0   1.0  99.0
2013-01-03  -0.917904   0.333546   0.345352   2.0   2.0  99.0
2013-01-04   0.028661   1.251974  -0.201867   3.0   3.0  99.0
2013-01-05   0.866957   1.534359   0.834069   4.0   4.0  99.0
2013-01-06  99.000000  99.000000  99.000000  99.0  99.0  99.0

In [80]:
# isna
df1.isna()

A      B      C      D      F      E
2013-01-01  False  False  False  False  False  False
2013-01-02  False  False  False  False  False   True
2013-01-03  False  False  False  False  False   True
2013-01-04  False  False  False  False  False   True
2013-01-05  False  False  False  False  False   True
2013-01-06   True   True   True   True   True   True

In [81]:
df1[df1.isna()] = 99
df1

A          B          C     D     F     E
2013-01-01  -0.107059   0.123826   1.494973   0.0  -1.0   1.0
2013-01-02   0.000000  11.000000   0.740508   1.0   1.0  99.0
2013-01-03  -0.917904   0.333546   0.345352   2.0   2.0  99.0
2013-01-04   0.028661   1.251974  -0.201867   3.0   3.0  99.0
2013-01-05   0.866957   1.534359   0.834069   4.0   4.0  99.0
2013-01-06  99.000000  99.000000  99.000000  99.0  99.0  99.0

## Operations

### opearation can be done in two ways:
### `df + x`
* + can be +, -, \ ,* .....
* x can be:
    * df
    * a series or 1D-array or 1D-list (having same lenth as the columns)
### using the name of the opeation: `DataFrame.add(x, axis=)
* the axis: raw:0, columns:1

In [116]:
# Statistcs: mean, std, count, ...
print(df.mean(axis=0)) # axis=0 accross columns, axis=1 accross raws
print(df.describe().loc['mean', :])

# but we can not get the mean for raws
df.mean(axis=1)

A    0.129755
B    2.563284
C    0.236424
D    2.500000
F    3.000000
dtype: float64
A    0.129755
B    2.563284
C    0.236424
D    2.500000
F    3.000000
Name: mean, dtype: float64


2013-01-01    0.377935
2013-01-02    2.748102
2013-01-03    0.752199
2013-01-04    1.415754
2013-01-05    2.247077
2013-01-06    2.049878
Freq: D, dtype: float64

In [117]:
df.describe().loc['mean',:]

A    0.129755
B    2.563284
C    0.236424
D    2.500000
F    3.000000
Name: mean, dtype: float64

In [118]:
s = pd.Series([1, 3, 5, np.nan, 8, 8], index=df.index)
print(s)
s = s.shift(2)
print(f'\n{s}')


# subtracting s form each column
df.sub(s, axis='index') # axis: index: 0, columns: 1

2013-01-01    1.0
2013-01-02    3.0
2013-01-03    5.0
2013-01-04    NaN
2013-01-05    8.0
2013-01-06    8.0
Freq: D, dtype: float64

2013-01-01    NaN
2013-01-02    NaN
2013-01-03    1.0
2013-01-04    3.0
2013-01-05    5.0
2013-01-06    NaN
Freq: D, dtype: float64


A         B         C    D    F
2013-01-01       NaN       NaN       NaN  NaN  NaN
2013-01-02       NaN       NaN       NaN  NaN  NaN
2013-01-03 -1.917904 -0.666454 -0.654648  1.0  1.0
2013-01-04 -2.971339 -1.748026 -3.201867  0.0  0.0
2013-01-05 -4.133043 -3.465641 -4.165931 -1.0 -1.0
2013-01-06       NaN       NaN       NaN  NaN  NaN

In [119]:
# applying operating in diffrent way:
sub = df - np.arange(df.shape[1])
print(sub)
# broad casting
sub2 = df.sub(np.arange(df.shape[1]), axis=1)
sub2 == sub

                   A          B         C  D    F
2013-01-01 -0.107059  -0.876174 -0.505027 -3  NaN
2013-01-02  0.000000  10.000000 -1.259492 -2 -3.0
2013-01-03 -0.917904  -0.666454 -1.654648 -1 -2.0
2013-01-04  0.028661   0.251974 -2.201867  0 -1.0
2013-01-05  0.866957   0.534359 -1.165931  1  0.0
2013-01-06  0.907876   0.136002 -3.794488  2  1.0


A     B     C     D      F
2013-01-01  True  True  True  True  False
2013-01-02  True  True  True  True   True
2013-01-03  True  True  True  True   True
2013-01-04  True  True  True  True   True
2013-01-05  True  True  True  True   True
2013-01-06  True  True  True  True   True

In [120]:
# data frame
df2 = df.copy()
df - df2

A    B    C  D    F
2013-01-01  0.0  0.0  0.0  0  NaN
2013-01-02  0.0  0.0  0.0  0  0.0
2013-01-03  0.0  0.0  0.0  0  0.0
2013-01-04  0.0  0.0  0.0  0  0.0
2013-01-05  0.0  0.0  0.0  0  0.0
2013-01-06  0.0  0.0  0.0  0  0.0

## Apply `DataFrame.apply(func, axis=0, raw=False, result_type=None, args=(), **kwargs)` [link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.apply.html)
* args: tuple input to the func


In [123]:
df.apply(lambda x: x.max() - x.min(), axis=0)

A     1.825780
B    10.876174
C     3.289461
D     5.000000
F     4.000000
dtype: float64

In [124]:
df.apply(lambda x: x.max() - x.min(), axis=1)

2013-01-01     1.602032
2013-01-02    11.000000
2013-01-03     2.917904
2013-01-04     3.201867
2013-01-05     3.165931
2013-01-06     6.794488
Freq: D, dtype: float64

In [125]:
print(df)
df.apply(np.sqrt)

                   A          B         C  D    F
2013-01-01 -0.107059   0.123826  1.494973  0  NaN
2013-01-02  0.000000  11.000000  0.740508  1  1.0
2013-01-03 -0.917904   0.333546  0.345352  2  2.0
2013-01-04  0.028661   1.251974 -0.201867  3  3.0
2013-01-05  0.866957   1.534359  0.834069  4  4.0
2013-01-06  0.907876   1.136002 -1.794488  5  5.0


A         B         C         D         F
2013-01-01       NaN  0.351889  1.222691  0.000000       NaN
2013-01-02  0.000000  3.316625  0.860528  1.000000  1.000000
2013-01-03       NaN  0.577534  0.587666  1.414214  1.414214
2013-01-04  0.169296  1.118917       NaN  1.732051  1.732051
2013-01-05  0.931106  1.238692  0.913274  2.000000  2.000000
2013-01-06  0.952825  1.065834       NaN  2.236068  2.236068

In [126]:
df.apply(np.sum, axis=0)

A     0.778532
B    15.379707
C     1.418546
D    15.000000
F    15.000000
dtype: float64

In [142]:
def apply_func(raw, norm=1):
    return (raw.max() - raw.min())/norm

df.apply(func=apply_func, args=(100,), axis=0)

A    0.018258
B    0.108762
C    0.032895
D    0.050000
F    0.040000
dtype: float64

### histogram `Datagrame/Series.values_count()`

In [144]:
s = pd.Series(np.random.randint(0, 7, size=10))
print(s)
s.value_counts()

0    2
1    5
2    4
3    0
4    0
5    2
6    0
7    5
8    1
9    2
dtype: int64


2    3
0    3
5    2
4    1
1    1
dtype: int64

## Strings [link](https://pandas.pydata.org/docs/user_guide/text.html#text-string-methods)
All the string methos is under `Dataframe/Series.str.opeation`

In [145]:
s = pd.Series(["A", "B", "C", "Aaba", "Baca", np.nan, "CABA", "dog", "cat"])
s.str.lower()


0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

## Merging

### `pandas.concat(objs, *, axis=0, join='outer', ignore_index=False, keys=None, levels=None, names=None, verify_integrity=False, sort=False, copy=True)`[link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html?highlight=concate)

Adding columns to Dataframe is fast,but adding raws it typically slow so they recommnet donig this outsied pandas

In [158]:
df = pd.DataFrame(np.random.randn(10, 4), columns=['a', 'b', 'c', 'd'])
print(df)

pieces = df[:1], df[1:3], df[4:5]
pd.concat(list(pieces)) # list or tupple same

          a         b         c         d
0 -0.790366 -1.725771  0.375939 -1.217748
1  0.201314  0.542893  0.157019 -0.670727
2 -1.311574  0.964253 -1.164238  1.032226
3 -0.844743  1.497881  0.035496 -0.479168
4  1.141810  0.587236 -0.100020  0.206632
5 -0.720773  1.111387 -0.410293 -1.538744
6 -1.253485  0.303893 -0.951926  0.072205
7  0.228222  0.803235 -0.019661 -0.223734
8  0.860534 -1.004568 -0.943798  0.632581
9  0.485390  0.300724 -1.146221 -0.951485


a         b         c         d
0 -0.790366 -1.725771  0.375939 -1.217748
1  0.201314  0.542893  0.157019 -0.670727
2 -1.311574  0.964253 -1.164238  1.032226
4  1.141810  0.587236 -0.100020  0.206632

In [161]:
cols = df.iloc[:, 0], df.iloc[:, -1]
pd.concat(cols, axis=1)

a         d
0 -0.790366 -1.217748
1  0.201314 -0.670727
2 -1.311574  1.032226
3 -0.844743 -0.479168
4  1.141810  0.206632
5 -0.720773 -1.538744
6 -1.253485  0.072205
7  0.228222 -0.223734
8  0.860534  0.632581
9  0.485390 -0.951485

### Joing two dataframs `pandas.merge(left, right, how='inner', on=None, left_on=None, right_on=None, left_index=False, right_index=False, sort=False, suffixes=('_x', '_y'), copy=True, indicator=False, validate=None)`  [link](https://pandas.pydata.org/docs/reference/api/pandas.merge.html#pandas.merge)

Database joining style: applying a merging over same columns

In [175]:
left = pd.DataFrame({"TheName": ["foo", "foo"], "leftVal": [1, 2]})
right = pd.DataFrame({"TheName": ["foo", "foo"], "RightVal": [4, 5]})


print(pd.merge(left, right, on=['TheName']))
pd.concat([left, right], axis=1) 
# on= a list of indexNames, or columnsName (i.e: labels)

  TheName  leftVal  RightVal
0     foo        1         4
1     foo        1         5
2     foo        2         4
3     foo        2         5


TheName  leftVal TheName  RightVal
0     foo        1     foo         4
1     foo        2     foo         5

In [176]:
left = pd.DataFrame({"TheName": ["foo", "bar"], "leftVal": [1, 2]})
right = pd.DataFrame({"TheName": ["foo", "bar"], "RightVal": [4, 5]})


pd.merge(left, right, on=['TheName'])

TheName  leftVal  RightVal
0     foo        1         4
1     bar        2         5

## Grouping 

In [189]:
df = pd.DataFrame(
    {
        "A": ["foo", "bar", "foo", "bar", "foo", "bar", "foo", "foo"],
        "B": ["one", "one", "two", "three", "two", "two", "one", "three"],
        "C": np.arange(8),
        "D": np.arange(8)*10,
    }
)
df

A      B  C   D
0  foo    one  0   0
1  bar    one  1  10
2  foo    two  2  20
3  bar  three  3  30
4  foo    two  4  40
5  bar    two  5  50
6  foo    one  6  60
7  foo  three  7  70

In [191]:
print(df.groupby('A'))
df.groupby('A')[['C', 'D']].sum()
# all sum of (raws['C']) == bar = 9

C    D
A           
bar   9   90
foo  19  190

In [192]:
df.groupby(['A', 'B'])[['C', 'D']].sum()

C   D
A   B           
bar one    1  10
    three  3  30
    two    5  50
foo one    6  60
    three  7  70
    two    6  60